### PR TITLE
Fix to question?

### PR DESCRIPTION
**Pull request by keflavich**
Hi Grant,
   I think the fit *did* work, and you just need to change the plotting limits
to see the lower part of the fit.  If I missed something, could you explain
which part you think is not working?
   Also, in your example, I didn't see the actual 'specfit' call - did you
delete that after running it?

### CODE REVIEW

**Comment by keflavich** [comment]
Oops, no, now I see the problem - you're trying to fit all 3 lines, and only 1 is fitting.  Investigating...

**Comment by granttremblay** [comment]
Yup! That was the problem - I'm trying to fit all three simultaneously (see where I populate my guess list). 

Thanks so much for looking into this Adam!

**Comment by keflavich** [comment]
OK, so I can't tell you what the problem with your script was exactly because you left out the `sp.specfit` call.  However, the problem in  *my* version was that I used an incorrect keyword `guess` instead of the correct keyword `guesses`.  I'll update pyspeckit to check for both.

**Comment by granttremblay** [comment]
Uh, whoops! I must've deleted the cell where I actually ran sp.specfit (I cleaned up my notebook to only show you the essentials - I had tried things like baseline fitting, etc, but deleted those cells). 

this is the cell I deleted, FYI. I know I'm probably no longer supposed to use multifit separately. But sp.specfit wasn't working, so I was just testing multifit...

```
sp.specfit.selectregion(fit_plotted_area=True)
sp.specfit.multifit(guesses=guesses)
sp.specfit.print_fit()
```

**Comment by keflavich** [comment]
OK, I get something pretty wacky if I do that.

**Comment by keflavich** [comment]
Oh, but it's because the 'guesses' variable got changed.  More investigating happening...

**Comment by keflavich** [comment]
weird.  I got it to work once but not repeatably.  There's some bug here.

**Comment by granttremblay** [comment]
Yes! that was my problem too! 

It worked once or twice, but the successful fit was absolutely not repeatable. I'd re-run the identical cell, and the fit would suddenly go all wonky.

**Comment by keflavich** [comment]
argh.  I know *part* of the reason, but not the whole reason.  have to finish debugging after lunch

**Pull request merged**
